### ISSUE TITLE
several build issues

### ISSUE THREAD

**Issue by consultit** [fbb-git/icmake#3]
I'm trying to install from source (on debian 8 - jessie).
When executing "./icm_bootstrap x" are the errors reported in the file icm_bootstrap_err1.log.
Exporting "-std gnu99 =" or "= -std gnu11" are the errors reported in the file icm_bootstrap_err2.log.
Exporting "-std = c99" or "-std = c11" are the errors reported in the file icm_bootstrap_err3.log.
[icm_bootstrap_err1.log.zip](https://github.com/fbb-git/icmake/files/72418/icm_bootstrap_err1.log.zip)
[icm_bootstrap_err2.log.zip](https://github.com/fbb-git/icmake/files/72419/icm_bootstrap_err2.log.zip)
[icm_bootstrap_err3.log.zip](https://github.com/fbb-git/icmake/files/72420/icm_bootstrap_err3.log.zip)

**Comment by fbb-git** [comment]
Dear consultit, you wrote:

> I'm trying to install from source (on debian 8 - jessie)
> When executing "/icm_bootstrap x" are the errors reported in the file icm_bootstrap_err1log
> Exporting "-std gnu99 =" or "= -std gnu11" are the errors reported in the file icm_bootstrap_err2log
> Exporting "-std = c99" or "-std = c11" are the errors reported in the file icm_bootstrap_err3log
> [icm_bootstrap_err1logzip](https://githubcom/fbb-git/icmake/files/72418/icm_bootstrap_err1logzip)
> [icm_bootstrap_err2logzip](https://githubcom/fbb-git/icmake/files/72419/icm_bootstrap_err2logzip)
> 
> [icm_bootstrap_err3logzip](https://githubcom/fbb-git/icmake/files/72420/icm_bootstrap_err3logzip)

Thank you for your report about compiling icmake. 

Jessie's gcc compiler is currently at version 4.9.2, compared to, e.g.,
stretch, which offers 5.3.1. So stretch (testing) offers a major version
upgrade as compared to Jessie (stable). I suggest you upgrade to a more recent
compiler, or -maybe easier- install the icmake package which can be installed
using, e.g., apt-get install icmake.

Unfortunately you didn't list the commands you issued, which makes it hard to
figure out what happened. It's unlikely that you executed '/icm_bootstrap x'
as that suggests you executed the command from the root-directory of your file
system, which would be highly unusual.

(As an aside, please note that you reported urls starting with
https://githubcom/fbb-git/icmake/: 'githubcom', however, does not exist, but
'github.com' does.)

When I run the commands 

```
./icm_prepare /
```

and then

```
./icm_bootstrap x
```

I do not encounter any issues. E.g., here's what I get:

```
$ ./icm_prepare /
Creating the intermediate destination directory ./tmp
and removing any old files
Writing tmp/ROOT
Creating remaining intermediate destination directories

$ ./icm_bootstrap x
Creating tmp/libicrss.a
..ar: creating ../tmp/libicrss.a
..
Creating tmp//usr/bin/icmake
..
Creating tmp//usr/bin/icmun
..
Creating tmp//usr/lib/icmake/icm-pp
...........
Creating tmp//usr/lib/icmake/icm-comp
.........
Creating tmp//usr/lib/icmake/icm-exec
..............
./scripts to ./tmp
skeleton files to tmp//usr/share/icmake
configuration files to tmp//etc/icmake
man-pages to tmp//usr/share/man/man1 and .../man7
documentation to tmp//usr/share/doc/icmake and tmp//usr/share/doc/icmake-doc
./etc files to tmp/etc/
Done.
```

I ran the commands, showing exactly identical results, on i386 and amd64
architectures, so other than the advice to upgrade your compiler or to use
'apt-get install icmake' there's not very much I can do right now to help you
out. 

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by consultit** [comment]
Hi fbb-git,
sorry for partial information.
Here are the shell commands I used to build icmake:

```
$ git clone https://github.com/fbb-git/icmake.git
$ cd icmake/icmake/
$ ./icm_prepare /
$ ./icm_bootstrap x
```

The version of debian jessie is stable (no packages from testing or unstable releases).
BTW I also tried on Ubuntu 14.04 (also stable version) and I got similar errors.
Bye

**Comment by fbb-git** [comment]
Dear consultit, you wrote:

> Hi fbb-git,
> sorry for partial information.
> Here are the shell commands I used to build icmake:
> 
> ```
> $ git clone https://github.com/fbb-git/icmake.git
> $ cd icmake/icmake/
> $ ./icm_prepare /
> $ ./icm_bootstrap x
> ```
> 
> The version of debian jessie is stable (no packages from testing or unstable releases).
> BTW I also tried on Ubuntu 4.14 (also stable version) and I got similar errors.
> Bye

Thanks for the additional info. 

In the meantime I reran the installation scripts using an old 4.9 compiler,
and I can confirm your compilation errors. 

Since the errors are clearly related to an old compiler version, I suggest you
upgrade your compiler, or for the time being stick to icmake's version which
comes with Debian stable, which is 7.21.01. 

Github tagged versions before 8.00.00 compile OK with 4.9. E.g., I just ran
./icm_bootstrap / on tagged release 7.23.02, which is the last 7-release
before upgrading to versions 8.xx.yy, which compiles fine with gcc 4.9.3.

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by consultit** [comment]
Ok, I'll use the distribution package.
Bye

**Comment by fbb-git** [comment]
OK, thanks for your reactions. I'm closing the issue.
